### ISSUE TITLE
pv_estimate calculation

### ISSUE THREAD

**Issue by philippesikora** [SimonRafferty/ESP32-Solcast-API#1]
Great sketch running on ESP32. Congratulation -:)
However you need to multiply the final result by 0.5 as you doing the pv_estimate calculation with 30 minute resolution.

**Comment by SimonRafferty** [comment]
You're right!
I ended up not using Solcast, but https://api.forecast.solar instead.
Solcast is more accurate, particularly in the winter but the limited number of requests you can make per day made it impossible to debug my final automation.
At least this code gives you a start!

**Comment by SimonRafferty** [comment]
Thanks for pointing that out.  Now fixed.
